name: Publish To NPM
on:
  push:
    branches: [ main, vue-3 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v2

      - name: NPM install
        run: npm i

      - name: NPM build
        run: npm run build

      - name: Check if version has been updated
        id: check
        uses: EndBug/version-check@v1

      - name: Publish when changed
        if: steps.check.outputs.changed == 'true'
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
